#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# rules
# remove all rules first
bspc rule -a Chromium desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Scratchpad sticky=on state=floating hidden=on
