#! /bin/sh

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# rules
# remove all rules first
bspc rule -a Chromium desktop='^1'
bspc rule -a mpv state=floating
bspc rule -a scratch sticky=on state=floating hidden=on
bspc rule -a Emacs state=tiled
