#! /usr/bin/env bash

wid=$1
class=$(echo ${2} | xargs)
instance=$(echo ${3} | xargs)
title=$(xtitle "$wid")

# Debug
echo "$(date '+%D %T'): $wid $class $instance $title" >> /tmp/bspc-external-rules

if [ "$instance" = scratchmacs ] ; then
    case "$title" in
        scratchmacs)
            echo "state=floating"
            echo "sticky=on"
            echo "rectangle=904x561+508+259"
        ;;
    esac
fi
