#! /usr/bin/env bash

wid=$1
class=$(echo ${2} | xargs)
instance=$(echo ${3} | xargs)
title=$(xtitle "$wid")

# Debug
echo "$(date '+%D %T'): $wid $class $instance $title" >> /tmp/bspc-external-rules

if [ "$instance" = emacs ] ; then
    echo "                 : $title" >> /tmp/bspc-external-rules
    case "$title" in
	scratchmacs)
	    echo "state=floating"
	    echo "sticky=on"
        echo "center=on"
        echo "rectangle=971x600+199+90"
	    ;;
    esac
fi
