#!/usr/bin/env bash

case "$1" in
    -h|--hide)
        D=$(bspc query -D -d focused --names)
        W=$(bspc query -N -n focused)
        bspc query -D --names | grep -q "'$D" || bspc monitor --add-desktops "'$D"
        bspc node "$W" --to-desktop "'$D"
        ;;

    -r|--retrieve)
        D=$(bspc query -D -d focused --names)
        if [[ -n $(bspc query -D --names | grep "'$D") ]];  then
            for i in $(bspc query -N -d \'$D); do
                bspc node "$i" -d "$D" -f
                break
            done
            (( $(bspc query -N -d \'$D| wc -l) )) || bspc desktop "'$D" -r
        fi
        ;;
    *) exit
esac
