#!/usr/bin/env bash

id=$(xdotool search --limit 1 --name "scratchmacs")

if [ -z "$id" ]; then
    emax --frame-parameters='(quote (name . "scratchmacs"))' \
         "/home/niels/org/todo.org" &
    id=$(xdotool search --limit 1 --name "scratchmacs")
fi

cur_desk=$(bspc query -D -d focused)
bspc node "$id" -d "$cur_desk"
bspc node "$id" --flag "hidden" -f
