#!/usr/bin/env bash

id=$(xdotool search --class scratchterm)

if [ -z "$id" ]; then
    st -c scratchterm
    id=$(xdotool search --class scratchterm)
fi

cur_monitor=$(bspc query -M -m focused)

bspc node "$id" --flag "hidden" -m "$cur_monitor" -f
