#!/usr/bin/env bash

id=$(xdotool search --limit 1 --name "scratchmacs")

if [ -z "$id" ]; then
    emacsclient --alternate-editor="" \
                --no-wait \
		--create-frame \
		--frame-parameters='(quote (name . "scratchmacs"))' \
		"/home/niels/org/todo.org" &
    id=$(xdotool search --limit 1 --name "scratchmacs")
fi

bspc node "$id" --flag "hidden" -f
