#!/usr/bin/env bash

id=$(xdotool search --limit 1 --name "scratchmacs")

if [ -z "$id" ]; then
    emax --frame-parameters='(quote (name . "scratchmacs"))' &
    id=$(xdotool search --limit 1 --name "scratchmacs")
fi

cur_desk=$(bspc query -D -d focused)
cur_monitor=$(bspc query -M -m focused)

bspc node "$id" -d "$cur_desk" -m "$cur_monitor"
bspc node "$id" --flag "hidden" -f
