((python-mode (eglot-workspace-configuration .
                                     ((pyls . ((configurationSources . ["flake8"])
                                               (plugins . ((jedi_completion . ((enabled . t)))
                                                           (jedi_definition . ((enabled . t)
                                                                               (follow_imports . t)
                                                                               (follow_builtin_imports . t)))
                                                           (jedi_hover . ((enabled . t)))
                                                           (jedi_signature_help . ((enabled . t)))
                                                           (jedi_symbols . ((enabled . t)
                                                                            (all_scopes . t)))
                                                           (mypy . ((enabled . t)))
                                                           (pylint . ((enabled . nil)))
                                                           (pycodestyle . ((enabled . nil)))
                                                           (pydocstyle . ((enabled . nil)))
                                                           (pyflakes . ((enabled . nil)))
                                                           ))))))
              (pyvenv-activate . ".venv")))
